// This file should be autogenerated.

import { ShellComponent } from './app/shell/shell';
import { ProductList } from './app/components/product-list/product-list';
import { ProductAlerts } from './app/components/product-alerts/product-alerts';
import { Index } from './app/pages/index/index';
import { Products_id } from './app/pages/products/_id';
import { ProductDetails } from './app/components/product-details/product-details';
import { Cart } from './app/pages/cart';
import { Shipping } from './app/pages/shipping';

// Map of custom element name to component class to be used in server
// where we don't lazily load code.
export const ELEMENTS_MAP = {
  'shell-root': ShellComponent,
  'page-index': Index,
  'page-products-id': Products_id,
  'page-cart': Cart,
  'page-shipping': Shipping,
  'app-product-list': ProductList,
  'app-product-alerts': ProductAlerts,
  'app-product-details': ProductDetails,
};
