// This file should be autogenerated.

import { ShellComponent } from './app/shell/shell';
import { LinkHeader } from './app/components/link-header/link-header';
import { Index } from './app/pages/index/index';
import { About } from './app/pages/about/about';
import { Greeting } from './app/components/greeting/greeting';

// Map of custom element name to component class to be used in server
// where we don't lazily load code.
export const ELEMENTS_MAP = {
  'shell-root': ShellComponent,
  'page-index': Index,
  'page-about': About,
  'app-link-header': LinkHeader,
  'app-greeting': Greeting,
};
