// This file should be autogenerated.

import { ShellComponent } from './app/shell/shell';
import { Index } from './app/pages/index/index';
import { MuiAppbar } from './app/components/mui-appbar/mui-appbar';

// Map of custom element name to component class to be used in server
// where we don't lazily load code.
export const ELEMENTS_MAP = {
  'shell-root': ShellComponent,
  'page-index': Index,
  // 'mui-appbar': MuiAppbar,
};
